export enum UserType {
    SENDER = "SENDER",
    DISPATCHER = "DISPATCHER",
    ADMIN = "ADMIN", 
}

export enum Gender {
    MALE = "SENDER",
    FEMALE = "FEMALE",
    OTHER = "OTHER", 
}

export enum DEPOSIT_STATUS {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    DECLINED = 'DECLINED'
}

export enum DEPOSIT_TRXNSTATUS {
    FAILED = 'FAILED',
    SUCCESSFUL = 'SUCCESSFUL',
}

export enum WALLET_STATUS {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    BLOCKED = "BLOCKED",
    DELETED = "DELETED"
}

export enum PACKAGE_STATUS {
    ARRIVED = "ARRIVED",
    CHECKEDOUT = "CHECKEDOUT",
    CONFIRMED = "CONFIRMED",
    DELIVERED = "DELIVERED",
    PENDING = "PENDING",
    PICKEDUP = "PICKEDUP",
    SHIPPED = "SHIPPED"
}